baseurl = "/"
title = "Six Nations Food"
languageCode = "en-us"
paginate = "10" # Number of posts per page
relativeURLs = true
theme = "mediumish-gohugo-theme"
summaryLength = 25
copyright = "Helen and Jeff"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id

[blackfriday]
  extensions = ["hardLineBreak"]

[Author]
  name = "Helen and Jeff"
  bio = "We like rugby and food and taking concepts too far."
  avatar = "img/avatar.png"

[Params]
  logo = "/images/logo.png"
  subtitle = "Combining foods whether they like it or not since 2014" # Subtitle of your site
  description = "A blog about rugby, food, and tenuous mash-ups" # Description of your site
  opengraph = true
  twitter_cards = false
  readmore = false # Show "Read more" button in list if true
  authorbox = false
  post_navigation = true
  post_meta = ["date", "categories"] # Order of post meta information

[Params.index]
   picture = "/images/author.jpg"
   title = "Six nations food - the blog"
   subtitle = "All the recipes you never knew you wanted, for combinations that should never have existed"
   altertbar = true

[[menu.main]]
    name = "Blog posts"
    weight = 100
    identifier = "posts"
    url = "/posts"
